from .base import BaseView
from .machines import NetworkView
from .machine_detail import MachineDetailView
from .domain_list import DomainListView
from .domain_detail import DomainDetailView
from .evidence_list import EvidenceListView
from .evidence_detail import EvidenceDetailView
from .credential_list import CredentialListView
from .credential_detail import CredentialDetailView
from .users import UsersView
from .user_detail import UserDetailView
from .passwords import PasswordsView
from .hash_list import HashListView
from .hash_detail import HashDetailView
from .shell_list import ShellListView
from .shell_detail import ShellDetailView
from .ssh_detail import SSHDetailView
from .reverse_shell_detail import ReverseShellDetailView
from .tools import ToolsView
from .inventory import InventoryView
